select/unselect all button #4972
GitStartHQ/graphql-engine pull request #1
Opened 2022-06-15 17:14 UTC by sauzzon

### Description

### Changelog

- [ ] `CHANGELOG.md` is updated with user-facing content relevant to this PR. If no changelog is required, then add the `no-changelog-required` label.

### Affected components

- [ ] Server
- [ ] Console
- [ ] CLI
- [ ] Docs
- [ ] Community Content
- [ ] Build System
- [ ] Tests
- [ ] Other (list it)

### Related Issues

### Solution and Design

### Steps to test and verify

### Limitations, known bugs & workarounds

### Server checklist

#### Catalog upgrade

Does this PR change Hasura Catalog version?
- [ ] No
- [ ] Yes
  - [ ] Updated docs with SQL for downgrading the catalog 

#### Metadata

Does this PR add a new Metadata feature?
- [ ] No
- [ ] Yes
  - Does `run_sql` auto manages the new metadata through schema diffing?
    - [ ] Yes
    - [ ] Not required
  - Does `run_sql` auto manages the definitions of metadata on renaming?
    - [ ] Yes
    - [ ] Not required
  - Does `export_metadata`/`replace_metadata` supports the new metadata added?
    - [ ] Yes
    - [ ] Not required

#### GraphQL
- [ ] No new GraphQL schema is generated
- [ ] New GraphQL schema is being generated:
   - [ ] New types and typenames are correlated
   
   

#### Breaking changes

- [ ] No Breaking changes
- [ ] There are breaking changes:

  1. Metadata API

     Existing `query` types:
     - [ ] Modify `args` payload which is not backward compatible
     - [ ] Behavioural change of the API
     - [ ] Change in response `JSON` schema
     - [ ] Change in error code
     

  2. GraphQL API

     Schema Generation:
     
     
     - [ ] Change in any `NamedType`
     - [ ] Change in table field names
     

     Schema Resolve:-
     
     - [ ] Change in treatment of `null` value for any input fields 
     

  3. Logging

     - [ ] Log `JSON` schema has changed
     - [ ] Log `type` names have changed

2022-06-17 08:17 UTC, bipsBro requested changes
Need some clarification.

2022-06-17 08:17 UTC, bipsBro commented on server/src-lib/Hasura/GraphQL/Parser/Class.hs
> -    (HasCallStack, Ord a, Typeable p, Typeable a, Typeable b) =>
Why did you remove this @sauzzon?

2022-06-17 08:17 UTC, bipsBro commented on server/src-lib/Hasura/GraphQL/Parser/Class.hs
>  memoize name f a = memoizeOn name a (f a)
Are these necessary changes?

2022-06-17 08:17 UTC, bipsBro commented on server/src-lib/Hasura/GraphQL/Parser/Class.hs
> -import Hasura.GraphQL.Parser.Internal.Types
any reason to remove this @sauzzon ?

2022-06-17 08:44 UTC, sauzzon commented on server/src-lib/Hasura/GraphQL/Parser/Class.hs
> -    (HasCallStack, Ord a, Typeable p, Typeable a, Typeable b) =>
it wasn't done by me. Sync issues

2022-06-17 08:45 UTC, sauzzon commented on server/src-lib/Hasura/GraphQL/Parser/Class.hs
> -import Hasura.GraphQL.Parser.Internal.Types
it wasn't done by me. Sync issues

2022-06-17 08:45 UTC, sauzzon commented on server/src-lib/Hasura/GraphQL/Parser/Class.hs
>  memoize name f a = memoizeOn name a (f a)
it wasn't done by me. Sync issues

2022-07-06 03:39 UTC, sudeshna-22 approved these changes

2022-07-06 04:16 UTC, shrestharajani approved these changes

2022-07-20 06:34 UTC, closed without merging