console: converting routes.js and server.js to typescript fix #4314
GitStartHQ/graphql-engine pull request #8
Opened 2022-06-23 07:29 UTC by sudeshna-22

### Description

### Changelog

- [ ] `CHANGELOG.md` is updated with user-facing content relevant to this PR. If no changelog is required, then add the `no-changelog-required` label.

### Affected components

- [ ] Server
- [ ] Console
- [ ] CLI
- [ ] Docs
- [ ] Community Content
- [ ] Build System
- [ ] Tests
- [ ] Other (list it)

### Related Issues

### Solution and Design

### Steps to test and verify

### Limitations, known bugs & workarounds

### Server checklist

#### Catalog upgrade

Does this PR change Hasura Catalog version?
- [ ] No
- [ ] Yes
  - [ ] Updated docs with SQL for downgrading the catalog 

#### Metadata

Does this PR add a new Metadata feature?
- [ ] No
- [ ] Yes
  - Does `run_sql` auto manages the new metadata through schema diffing?
    - [ ] Yes
    - [ ] Not required
  - Does `run_sql` auto manages the definitions of metadata on renaming?
    - [ ] Yes
    - [ ] Not required
  - Does `export_metadata`/`replace_metadata` supports the new metadata added?
    - [ ] Yes
    - [ ] Not required

#### GraphQL
- [ ] No new GraphQL schema is generated
- [ ] New GraphQL schema is being generated:
   - [ ] New types and typenames are correlated
   
   

#### Breaking changes

- [ ] No Breaking changes
- [ ] There are breaking changes:

  1. Metadata API

     Existing `query` types:
     - [ ] Modify `args` payload which is not backward compatible
     - [ ] Behavioural change of the API
     - [ ] Change in response `JSON` schema
     - [ ] Change in error code
     

  2. GraphQL API

     Schema Generation:
     
     
     - [ ] Change in any `NamedType`
     - [ ] Change in table field names
     

     Schema Resolve:-
     
     - [ ] Change in treatment of `null` value for any input fields 
     

  3. Logging

     - [ ] Log `JSON` schema has changed
     - [ ] Log `type` names have changed

2022-06-24 07:07 UTC, aayushdura commented on console/src/routes.tsx
> +  console.log(store, 'storetype');
Please do remove these console logs

2022-06-24 08:32 UTC, sauzzon commented on console/package.json
> +    "watch-client": "node -r dotenv/config webpack/webpack-dev-server.js",
Don't commit this file

2022-06-27 10:42 UTC, sauzzon reviewed
Update PR with description, screenshots and video ( if any) , steps to test and so on.

2022-06-29 14:54 UTC, sauzzon requested changes
There are 3 commits that are done by other people. Revert those.

2022-06-29 14:54 UTC, sauzzon commented on rfcs/transforms.md
> +  , request_body  ::  Maybe TemplateText                  # Raw templating
Don't commit files that you haven't changed.

2022-06-30 05:20 UTC, shrestharajani commented on console/src/routes.tsx
> +    //   return {};
I think comments can be removed.

2022-07-20 06:34 UTC, closed without merging